export const artisanData = [
  "Generator repair",
  "Fridge repair",
  "CCTV installation",
  "Gardening",
  "Laundry",
  "Electrician",
  "Plumber",
  "Painter",
  "Tailor",
  "Cook",
  "More...",
];

export const artisanDataLg = [
  "Generator repair",
  "Fridge repair",
  "CCTV installation",
  "Cobler",
  "Gardening",
  "Hair dresser",
  "Laundry",
  "Pedicure",
  "Electrician",
  "Plumber",
  "Barber",
  "Cleaner",
  "Tailor",
  "Baker",
  "Painter",
  "Welder",
  "Nail tech",
  "Cook",
  "Carpenter",
  "More...",
];
